#!/usr/bin/env python3
"""Post cppulse analysis results as a GitHub PR comment.

Formats findings, health score, and risk data into a markdown comment.
Updates existing cppulse comment if one already exists (avoids spam).
"""

from __future__ import annotations

import argparse
import json
import urllib.request
import urllib.error
from pathlib import Path


COMMENT_MARKER = "<!-- cppulse-report -->"


def _load_json(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text())
    except (FileNotFoundError, json.JSONDecodeError):
        return None


def _health_emoji(score: float) -> str:
    if score > 70:
        return "🟢"
    if score >= 40:
        return "🟡"
    return "🔴"


def _risk_emoji(level: str) -> str:
    return {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(level, "⚪")


def build_comment(output_dir: Path, new_findings: int) -> str:
    """Build the markdown comment body from analysis output."""
    risk_data = _load_json(output_dir / "risk_scores.json")
    findings_data = _load_json(output_dir / "findings.json")
    roadmap_data = _load_json(output_dir / "roadmap.json")

    lines = [COMMENT_MARKER, "## cppulse Health Report", ""]

    # Health score
    if risk_data:
        hs = risk_data["health_score"]
        overall = hs["overall"]
        emoji = _health_emoji(overall)

        lines.append(f"{emoji} **Overall Health Score: {overall:.1f} / 100**")
        lines.append("")
        lines.append("| Category | Score |")
        lines.append("|----------|------:|")
        for cat, score in hs.get("by_category", {}).items():
            display = cat.replace("_", " ").title()
            lines.append(f"| {_health_emoji(score)} {display} | {score:.1f} |")
        lines.append("")

    # Findings summary
    if findings_data:
        summary = findings_data.get("summary", {})
        total = summary.get("total_findings", 0)
        by_sev = summary.get("by_severity", {})

        lines.append(f"### Findings: {total:,} total")
        sev_parts = []
        if by_sev.get("error", 0) > 0:
            sev_parts.append(f"🔴 {by_sev['error']} errors")
        if by_sev.get("warning", 0) > 0:
            sev_parts.append(f"🟡 {by_sev['warning']} warnings")
        if by_sev.get("info", 0) > 0:
            sev_parts.append(f"🔵 {by_sev['info']} info")
        if sev_parts:
            lines.append(" · ".join(sev_parts))
        lines.append("")

    # New findings (PR diff)
    if new_findings > 0:
        lines.append(f"### ⚠️ {new_findings} new finding(s) introduced in this PR")
        lines.append("")
    elif new_findings == 0 and findings_data:
        lines.append("### ✅ No new findings introduced")
        lines.append("")

    # Top risk files
    if risk_data:
        risks = sorted(
            risk_data.get("file_risks", []),
            key=lambda r: r.get("bug_probability", 0),
            reverse=True,
        )[:5]
        if risks:
            lines.append("<details>")
            lines.append("<summary>Top 5 riskiest files</summary>")
            lines.append("")
            lines.append("| File | Bug Probability | Risk |")
            lines.append("|------|----------------:|:----:|")
            for r in risks:
                short = r["file"].split("/")[-1]
                prob = r.get("bug_probability", 0)
                level = r.get("risk_level", "unknown")
                lines.append(
                    f"| `{short}` | {prob:.1%} | {_risk_emoji(level)} {level} |"
                )
            lines.append("")
            lines.append("</details>")
            lines.append("")

    # Roadmap summary
    if roadmap_data:
        items = roadmap_data.get("items", [])
        if items:
            total_hours = sum(i.get("estimated_hours", 0) for i in items)
            lines.append(
                f"📋 **Roadmap**: {len(items)} items · ~{total_hours:,.0f} estimated hours"
            )
            lines.append("")

    lines.append("---")
    lines.append("*Generated by [cppulse](https://github.com/manju89jay/cppulse)*")

    return "\n".join(lines)


def find_existing_comment(repo: str, pr: int, token: str) -> int | None:
    """Find an existing cppulse comment on the PR."""
    url = f"https://api.github.com/repos/{repo}/issues/{pr}/comments?per_page=100"
    req = urllib.request.Request(url, headers={
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    })
    try:
        with urllib.request.urlopen(req) as resp:
            comments = json.loads(resp.read())
            for c in comments:
                if COMMENT_MARKER in c.get("body", ""):
                    return c["id"]
    except urllib.error.URLError:
        pass
    return None


def post_or_update_comment(repo: str, pr: int, body: str, token: str) -> None:
    """Post a new comment or update existing one."""
    existing_id = find_existing_comment(repo, pr, token)

    if existing_id:
        url = f"https://api.github.com/repos/{repo}/issues/comments/{existing_id}"
        method = "PATCH"
    else:
        url = f"https://api.github.com/repos/{repo}/issues/{pr}/comments"
        method = "POST"

    data = json.dumps({"body": body}).encode()
    req = urllib.request.Request(url, data=data, method=method, headers={
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
        "Content-Type": "application/json",
    })

    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            print(f"Comment {'updated' if existing_id else 'posted'}: {result.get('html_url', '')}")
    except urllib.error.URLError as e:
        print(f"Failed to post comment: {e}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--repo", required=True)
    parser.add_argument("--pr", type=int, required=True)
    parser.add_argument("--new-findings", type=int, default=0)
    parser.add_argument("--token", required=True)
    args = parser.parse_args()

    body = build_comment(args.output_dir, args.new_findings)
    post_or_update_comment(args.repo, args.pr, body, args.token)


if __name__ == "__main__":
    main()
