#!/bin/bash
# PreCompact hook — called automatically before Claude Code compacts context
# Saves current session state so it survives compaction via auto-memory

TIMESTAMP=$(date '+%Y-%m-%d %H:%M')
STATE_FILE=".claude/session-state.md"

echo "# Auto-saved Session State — $TIMESTAMP" > "$STATE_FILE"
echo "" >> "$STATE_FILE"

echo "## Git Status" >> "$STATE_FILE"
git status --short 2>/dev/null >> "$STATE_FILE" || echo "(not a git repo)" >> "$STATE_FILE"
echo "" >> "$STATE_FILE"

echo "## Recent Commits" >> "$STATE_FILE"
git log --oneline -5 2>/dev/null >> "$STATE_FILE" || echo "(no commits)" >> "$STATE_FILE"
echo "" >> "$STATE_FILE"

echo "## Modified Files (uncommitted)" >> "$STATE_FILE"
git diff --name-only HEAD 2>/dev/null >> "$STATE_FILE" || echo "(none)" >> "$STATE_FILE"
echo "" >> "$STATE_FILE"

echo "## Note" >> "$STATE_FILE"
echo "This file was auto-generated by the PreCompact hook." >> "$STATE_FILE"
echo "For a full handoff summary, run the session-handoff skill manually." >> "$STATE_FILE"

echo "[save-session-state] State saved to $STATE_FILE"
